
{{- range $index, $repo := .Values.pgBackRestConfig.repos }}
{{- if $repo.s3 }}
{{- $secretExists := (lookup "v1" "Secret" $.Release.Namespace "pgbackrest-s3" ) }}
{{- if not $secretExists }}
apiVersion: v1
kind: Secret
metadata:
  name: pgbackrest-s3
type: Opaque
data:
  {{- $args := dict "s3" $repo.s3 "index" $index }}
  s3.conf: |-
        {{ include "postgres.s3" $args | b64enc }}
{{- end }}
{{- end }}
{{- end }}
