{{- /*
create configmap containing sql commands to run during posgtgres initialization
*/}}
{{- if .Values.databaseInitSQL }}
{{- $sqlConfigMap := (lookup "v1" "ConfigMap" .Release.Namespace .Values.databaseInitSQL.name  ) }}
{{- if not $sqlConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.databaseInitSQL.name }}
  labels: {{ include "crunchy-postgres.labels" . | nindent 6 }}
data:
  bootstrap.sql:
{{ toYaml .Values.databaseInitSQL.sql | indent 2 }}
{{- end }}
{{- end }}
