---
features:
  basicAuth: true
  oidcAuth: true

config:
  enabled: true
  configMap:
    BASICAUTH_ENABLED: "true"
    DB_ENABLED: "true"
    DB_PORT: "5432"
    KC_ENABLED: "true"
    KC_IDENTITYKEY: idir_user_guid
    KC_PUBLICKEY: >-
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwz4nqXMKFW+5WVFer7LalKRPeg7095S+fUurYFJQwpOQ5gMSRFvbLWNIVoXSrkRG33V0S3ZVfIwNkLPso/5l04sN9j7DgTwOTbWHZbkr/fL4R7eVi6AR5mjaakq4YgOeVGhBryUUyhLIRVUxnbKA36nph5nORHykDsccrEMRjtmVjzjo1a1Y23zU3nesEryq2fvbRKPaVQ+itQeia5ijZIUwzS4yeT2baF+xPFoMzJ4iHCaSzrYCTSNGLYHDm8T006kjfAcLfbbJjQtaPtgRVpi4g/F1eUrHLwO/AVycFiGjsJVEjPsYS44klubmSZWeATy57Y0wmR0WvNppnyIxewIDAQAB
    KC_REALM: cp1qly2d
    KC_SERVERURL: "https://oidc.gov.bc.ca/auth"
    OBJECTSTORAGE_BUCKET: egejyy
    OBJECTSTORAGE_TEMP_EXPIRESIN: "300"
    OBJECTSTORAGE_ENDPOINT: "https://nrs.objectstore.gov.bc.ca"
    # OBJECTSTORAGE_KEY: ~
    SERVER_BODYLIMIT: 30mb
    # SERVER_LOGFILE: ~
    SERVER_LOGLEVEL: http
    SERVER_PORT: "3000"

patroni:
  enabled: true
