---
features:
  basicAuth: true
  defaultBucket: false
  oidcAuth: true

autoscaling:
  enabled: true
  maxReplicas: 4

config:
  enabled: true
  configMap:
    BASICAUTH_ENABLED: "true"
    DB_PORT: "5432"
    KC_ENABLED: "true"
    KC_IDENTITYKEY: idir_user_guid,bceid_user_guid,github_id
    KC_PUBLICKEY: >-
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuy7zfh2ZgpDV5mH/aXyLDTddZK81rGakJcTy4KvCNOkDDxt1KAhW02lmbCo8YhHCOzjNZBp1+Vi6QiMRgBqAe2GTPZYEiV70aXfROGZe3Nvwcjbtki6HoyRte3SpqLJEIPL2F+hjJkw1UPGnjPTWZkEx9p74b9i3BjuE8RnjJ0Sza2MWw83zoQUZEJRGiopSL0yuVej6t2LO2btVdVf7QuZfPt9ehkcQYlPKpVvJA+pfeqPAdnNt7OjEIeYxinjurZr8Z04hz8UhkRefcWlSbFzFQYmL7O7iArjW0bsSvq8yNUd5r0KCOQkFduwZy26yTzTxj8OLFT91fEmbBBl4rQIDAQAB
    KC_REALM: standard
    KC_SERVERURL: "https://dev.loginproxy.gov.bc.ca/auth"
    # SERVER_LOGFILE: ~
    SERVER_LOGLEVEL: http
    SERVER_PORT: "3000"
    SERVER_PRIVACY_MASK: "true"
    SERVER_TEMP_EXPIRESIN: "300"

postgres:
  enabled: true

  # --------------------------------
  # --------crunchydb config: ------
  # --------------------------------

  # --- cluster resource allocation ----
  instances:
    replicas: 2
    dataVolumeClaimSpec:
      storage: 1Gi
      storageClassName: netapp-block-standard
    requests:
      cpu: 1m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  # -------- backups ---------
  # (move all in backups section to values-prod eventually)
  pgBackRest:
    # 'backups to "volume" are hard-coded (enabled) in the PostgresCluster template (see: repo1)
    retention: "2"
    retentionFullType: count
    repos:
      schedules:
        full: 0 8 * * *
        incremental: 0 0,4,12,16,20 * * *
      volume:
        # enable backups to volume (pvc)
        enabled: true
        accessModes: ReadWriteOnce
        storage: 64Mi
        storageClassName: netapp-file-backup
    # backups to S3 are also hard-coded in postgresCluster template (see repo2)
    s3:
      # enable backups to s3
      enabled: true
      createS3Secret: true
      s3Secret: s3-pgbackrest
      s3Path: "/habackup"
      s3UriStyle: path
      bucket: "bucketName"
      endpoint: "endpointName"
      region: "ca-central-1"
      key: "s3keyValue"
      keySecret: "s3SecretValue"
      fullSchedule: "0 9 * * *"
      incrementalSchedule: "0 1,5,13,17,21 * * *"

  # ------ pgBouncer-------
  proxy:
    pgBouncer:
      replicas: 2
