apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "coms.fullname" . }}
  labels:
    {{- include "coms.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    {{- include "coms.selectorLabels" . | nindent 4 }}
  strategy:
    resources:
      {{- toYaml .Values.resources | nindent 6 }}
    rollingParams:
      timeoutSeconds: 600
    type: Rolling
  template:
    metadata:
      labels:
        {{- include "coms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "coms.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          {{- with .Values.podSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: production
            {{- if .Values.config.configMap.BASICAUTH_ENABLED }}
            - name: BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "coms.fullname" . }}-basicauth-secret
            - name: BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "coms.fullname" . }}-basicauth-secret
            {{- end }}
            {{- if .Values.config.configMap.DB_ENABLED }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "coms.fullname" . }}-db-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "coms.fullname" . }}-db-secret
            {{- end }}
            {{- if .Values.config.configMap.KC_ENABLED }}
            - name: KC_CLIENTID
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "coms.fullname" . }}-keycloak-secret
            - name: KC_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "coms.fullname" . }}-keycloak-secret
            {{- end }}
            - name: OBJECTSTORAGE_ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "coms.fullname" . }}-objectstorage-secret
            - name: OBJECTSTORAGE_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "coms.fullname" . }}-objectstorage-secret
          envFrom:
            - configMapRef:
                name: {{ include "coms.fullname" . }}-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
