{{- $password := (randAlphaNum 32) | b64enc }}
{{- $username := (randAlphaNum 32) | b64enc }}

{{- $secretName := printf "%s-%s" (include "coms.configname" .) "basicauth" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if not $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ $secretName }}
  labels: {{ include "coms.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  password: {{ $password }}
  username: {{ $username }}
{{- end }}
