name: Push

env:
  ACRONYM: coms
  APP_NAME: common-object-management-service
  NAMESPACE_PREFIX: bb17f9

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  build:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    outputs:
      HAS_DOCKERHUB_SECRETS: ${{ steps.check-secrets.outputs.HAS_DOCKERHUB_SECRETS }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Dockerhub Secrets
        id: check-secrets
        run: |
          echo "::set-output name=HAS_DOCKERHUB_SECRETS::${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}"
      - name: Build & Push to GHCR
        uses: ./.github/actions/build-push-container
        with:
          context: .
          image_name: ${{ env.APP_NAME }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}

  push-additional-registries:
    name: Push to Additional Registries
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.HAS_DOCKERHUB_SECRETS == 'true' && github.event_name != 'pull_request'
    strategy:
      matrix:
        # secrets cannot be accessed here
        # use the secret name here, but reference the secrets in the steps below
        include:
          - dest_registry: docker.io
            dest_username: DOCKERHUB_USERNAME
            dest_token: DOCKERHUB_TOKEN
            source_registry: ghcr.io
            source_username: ${{ github.repository_owner }}
            source_token: GITHUB_TOKEN
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to Registry
        uses: ./.github/actions/push-to-registry
        with:
          image_name: ${{ env.APP_NAME }}
          source_registry: ${{ matrix.source_registry }}
          source_username: ${{ matrix.source_username }}
          source_token: ${{ secrets[matrix.source_token] }}
          dest_registry: ${{ matrix.dest_registry }}
          dest_username: ${{ secrets[matrix.dest_username] }}
          dest_token: ${{ secrets[matrix.dest_token] }}

  deploy-dev:
    name: Deploy to Dev
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Dev
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ env.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          job_name: master
          namespace_prefix: ${{ env.NAMESPACE_PREFIX }}
          namespace_environment: dev
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

  deploy-test:
    name: Deploy to Test
    environment: test
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy-dev
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Test
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ env.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          job_name: master
          namespace_prefix: ${{ env.NAMESPACE_PREFIX }}
          namespace_environment: test
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

  deploy-prod:
    name: Deploy to Prod
    environment: prod
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy-dev
      - deploy-test
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Prod
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ env.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          job_name: master
          namespace_prefix: ${{ env.NAMESPACE_PREFIX }}
          namespace_environment: prod
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
